import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginButton from "./LoginButton";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import LogoutButton from "./LogoutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session: any = await getServerSession(authOptions as any);
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link href="/">FORUM</Link>
          <Link href="/list">LIST</Link>
          {session && session.user && (
            <div
              style={{
                display: "flex",
                backgroundColor: "skyblue",
                alignItems: "center",
              }}
            >
              <div>{session.user.name}</div>
              <img
                src={session.user.image}
                alt="hi"
                style={{
                  width: "50px",
                }}
              />
              <LogoutButton />
            </div>
          )}
          {(!session || !session.user) && <LoginButton />}
        </div>
        {children}
      </body>
    </html>
  );
}
